### ISSUE TITLE
cz.alenkacz.db#postgres-scala_2.12;0.5.0: not found

### ISSUE THREAD

**Issue by karimagnusson** [alenkacz/postgres-scala#17]
Hi, I am excited about your library.
But I am having a problem adding it to my project with sbt.

UNRESOLVED DEPENDENCIES
cz.alenkacz.db#postgres-scala_2.12;0.5.0: not found

In my build.sbt:
"cz.alenkacz.db" %% "postgres-scala_2.12" % "0.5.0"

**Comment by dopatraman** [comment]
i am also running into this problem. Older releases don't work either.

I switched to this library: "com.github.mauricio" %% "postgresql-async" % "0.2.21"

It is one of the dependencies for alenkacz's library and seems to be more dependable.

**Comment by augi** [comment]
Are you sure that you have resolving this dependency using `jcenter` (instead of Maven Central) ? I can see all the versions published correctly: https://jcenter.bintray.com/cz/alenkacz/db/postgres-scala_2.12/

**Comment by alenkacz** [comment]
@dopatraman @karimagnusson I have put the information about the need to add a resolver in SBT (or repository in gradle) to readme, so let me know if you still have problems

**Comment by karimagnusson** [comment]
It worked, Thank you.
